### ISSUE TITLE
Using with matrix field

### ISSUE THREAD

**Issue by Bronskiy** [ConfluxGroup/craft-relationshipeditor#4]
Hi, how can I use it with a matrix field?

**Comment by dreadfullyposh** [comment]
From the readme, Relationship Editor works with Entries, Users, Categories and Assets.

While Matrix blocks are technically elements, the Matrix field works differently than the other element relationship fields. (i.e. you cannot re-use a Matrix block across two Matrix fields)  So, therefore Relationship Editor has not been build to work around that difference.

I'm not sure exactly what your use case is, so it's hard to give any suggestions.

**Comment by Bronskiy** [comment]
Just want to create something like booking feature. User can choose time on the entry page and to store it in the user profile inside matrix field: time + related entry.

**Comment by dreadfullyposh** [comment]
If you're only adding to the Matrix and not removing anything from it on the front end then the native entry form would work fine.

Otherwise I'd recommend you make a separate section for your bookings and add an entries field to the users to relate to them.

**Comment by Bronskiy** [comment]
Yep, trying to use native form now. Anyway I used your plugin for another feature in the project and it works perfect. Thank you so much

**Comment by dreadfullyposh** [comment]
Awesome that's great to hear!
