### ISSUE TITLE
Bug with requirePermission

### ISSUE THREAD

**Issue by bphippen** [ConfluxGroup/craft-relationshipeditor#5]
I found a couple bugs regarding the requirePermissions, it looks like craft is using the section->uid now instead of the sectionId for checking the permission.

Also on line 162 of SaveController.php there is an extra colon, the $permissionSuffix variable already contains the colon.

`$this->requirePermission('publishPeerEntries:' . $permissionSuffix);`

Thanks love the plugin btw!

**Comment by dreadfullyposh** [comment]
Thanks for letting me know. I'll take a look at these issues.

I'm glad it's working well for you otherwise. It was a huge help for me on several projects.

**Comment by dreadfullyposh** [comment]
Just pushed out 1.0.3 which should fix these couple issues.

**Comment by bphippen** [comment]
Amazingly quick! Just tested and works great, thanks!!
